---
title: "Extras (Interactive Visualizations)"
author: "Rayce Ramsay"
date: "2025-04-30"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---


```{r, include=FALSE}
knitr::opts_chunk$set(fig.pos = "H", warning=F, message=F)
```

```{r, include=FALSE}
# Load libraries
library(plotly)
library(widgetframe)
library(tidyverse)
```

```{r, include=FALSE}
### DATA LOADING AND PRE-PROCESSING ###

# Load goalies data
goalies = read_csv("../data/nhl_goalies_data.csv")

# Convert the invalid double columns in the goalies data to integers and create some factors
goalies = goalies |>
  mutate(
    across(
      c(seasonId, playerId, height, weight, draftYear, draftRound, draftOverall, assists, 
        gamesPlayed, gamesStarted, goals, goalsAgainst, losses, otLosses, penaltyMinutes,
        points, saves, shotsAgainst, shutouts, ties, timeOnIce, wins),
      as.integer
    ),
    across(
      c(birthCountryCode, isInHallOfFameYn, catches),
      as.factor
    )
  )

# Create column for checking whether a goalie was drafted or not
goalies = goalies |>
  mutate(
    drafted = !is.na(draftYear)
  )

# Create column for goalie age as of the beginning of the season (i.e. September 15th as per NHL Hockey Operations Guidelines)
goalies = goalies |>
  separate(seasonId, into = c("seasonStartYear", "seasonEndYear"), sep = 4,
           convert = T, remove = F) |>
  mutate(
    ageAtSeasonStart = as.integer(
      interval(birthDate, date(paste0(seasonStartYear, "-09-15"))) / years()
    )
  )

# Get the average goalie height minus 2 inches for every season
undersize_heights_per_season = goalies |>
  group_by(seasonId) |>
  summarize(
    undersize_threshold = mean(height) - 2
  ) |>
  ungroup()

# Create column classifying a goalie as undersized or not (i.e. <= 2" below average)
goalies = goalies |>
  left_join(undersize_heights_per_season, by = "seasonId") |>
  mutate(
    undersized = height <= undersize_threshold
  )

# Get established goalies
established_goalies = goalies |>
  filter(gamesPlayed >= 25 | (gamesPlayed >= 22 & seasonStartYear == 2024))
```


Below are some interactive visualizations using the extracted data.


## Number of Shutouts per NHL Season

```{r, echo=FALSE, fig.align='center', fig.cap="A line plot showing the total number of shutouts recorded per NHL season from 2000-01 to 2023-24. The number of shutouts has generally declined over time, with notable dips in shortened or disrupted seasons (e.g., 2004–05, 2012–13, and 2020–21)."}
plot = goalies |>
  filter(seasonStartYear <= 2023) |>
  rename(`Season Start` = seasonStartYear) |>
  group_by(`Season Start`) |>
  summarize(`Total Shutouts` = sum(shutouts)) |>
  ggplot(aes(x = `Season Start`, y = `Total Shutouts`)) +
  geom_line(color="lightblue") +
  geom_point(color="#000099") +
  theme_minimal() +
  labs(
    title = "Number of Shutouts per NHL Season",
    x = "Season",
    y = "Total Number of Shutouts"
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = "0"), str_pad(seq(1, 25, 2), 2, pad = "0"), sep = "-")
  ) +
  theme_minimal()

ggplotly(plot)
```


## Average Age of NHL Goalies per Season

```{r, echo=FALSE, fig.align='center', fig.cap="Trends in the average age of NHL goaltenders at the start of each season from 2000-01 to 2023-24. The average goaltender age has been stable over the past two decades, hovering between 27 and 28 years old."}
plot = goalies |>
  filter(seasonStartYear <= 2023) |>
  rename(`Season Start` = seasonStartYear) |>
  group_by(`Season Start`) |>
  summarize(`Mean Age` = mean(ageAtSeasonStart)) |>
  ggplot(aes(x = `Season Start`, y = `Mean Age`)) +
  geom_line(color="lightblue") +
  geom_point(color="#000099") +
  theme_minimal() +
  labs(
    title = "Average Age of NHL Goaltenders by Season",
    x = "Season",
    y = "Mean Age"
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = "0"), str_pad(seq(1, 25, 2), 2, pad = "0"), sep = "-")
  ) +
  scale_y_continuous(
    breaks = 18:40
  ) +
  theme_minimal()

ggplotly(plot)
```


## Average SV% of NHL Goaltenders by Season and Catching Handedness

```{r, include=FALSE}
plot_data = goalies |>
  filter(seasonStartYear <= 2023) |>
  rename(
    `Season Start` = seasonStartYear,
    Catches = catches
  ) |>
  group_by(`Season Start`, Catches) |>
  summarize(
    N = n(),
    `Mean SV%` = sum(saves) / sum(shotsAgainst),
    .groups = "drop"
  ) |>
  mutate(
    label = paste0(
      "Season: ", `Season Start`, "\n",
      "Catches: ", Catches, "\n",
      "Mean SV%: ", round(`Mean SV%`, 3), "\n",
      "N: ", N
    )
  )

plot = plot_data |>
  ggplot(aes(x = `Season Start`, y = `Mean SV%`, colour = Catches)) +
  geom_line() +
  geom_point(aes(text = label)) +
  theme_minimal() +
  labs(
    title = "Average SV% of NHL Goaltenders\nby Season and Catching Handedness",
    x = "Season",
    y = "Mean SV%",
    colour = "Catches"
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 6),
    labels = paste0("'", str_pad(seq(0, 24, 6), 2, pad = "0"))
  )
```

```{r echo=FALSE, fig.align='center', fig.cap="Average save percentage (SV%) of NHL goaltenders by season and catching handedness. While left-catching goalies are more common, both groups have shown similar performance trends over time, with no consistent advantage observed for either handedness. Differences may reflect sample size variability rather than meaningful performance gaps."}
ggplotly(plot, tooltip = "text")
```
