<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Rayce Ramsay" />

<meta name="date" content="2025-03-16" />

<title>Exploratory Data Analysis (EDA)</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">NHL Goalie Height Analysis</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="eda.html">EDA</a>
</li>
<li>
  <a href="modelling.html">Modelling</a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
<li>
  <a href="extras.html">Extras</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/rayceramsay/nhl-goalie-height-analysis">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Exploratory Data Analysis (EDA)</h1>
<h4 class="author">Rayce Ramsay</h4>
<h4 class="date">2025-03-16</h4>

</div>


<div id="research-questions" class="section level2">
<h2>Research Questions</h2>
<p>The purpose of my research is to analyze the impact of height on a
goaltenders performance in the NHL. In particular:</p>
<ol style="list-style-type: decimal">
<li><p>Have goalies in the NHL been getting shorter, taller, or no
trend? Does this differ by country of origin?</p></li>
<li><p>Do taller goalies in the NHL have more success (i.e. better SV%
and GAA) than shorter goalies?</p></li>
</ol>
</div>
<div id="setup" class="section level2">
<h2>Setup</h2>
<pre class="r"><code># Load libraries
library(tidyverse)
library(cowplot)
library(ggcorrplot)
library(kableExtra)</code></pre>
</div>
<div id="data-loading" class="section level2">
<h2>Data Loading</h2>
<pre class="r"><code># Load data extracted from the NHL APIs (extraction done in separate file)
goalies = read_csv(&quot;../data/nhl_goalies_data.csv&quot;)</code></pre>
<pre><code>## Rows: 2256 Columns: 34
## ── Column specification ────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr   (9): birthCity, birthCountryCode, birthStateProvinceCode, fullName, is...
## dbl  (24): draftOverall, draftRound, draftYear, height, playerId, weight, se...
## date  (1): birthDate
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre class="r"><code>prospects = read_csv(&quot;../data/nhl_goalie_prospects_data.csv&quot;)</code></pre>
<pre><code>## Rows: 869 Columns: 15
## ── Column specification ────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (8): positionCode, catches, lastAmateurClub, lastAmateurLeague, birthCi...
## dbl  (5): height, weight, midtermRank, finalRank, draftYear
## lgl  (1): international
## date (1): birthDate
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre class="r"><code># Check for import issues with NHL goalies data
dim(goalies)</code></pre>
<pre><code>## [1] 2256   34</code></pre>
<pre class="r"><code>head(goalies)</code></pre>
<pre><code>## # A tibble: 6 × 34
##   birthCity  birthCountryCode birthDate  birthStateProvinceCode draftOverall
##   &lt;chr&gt;      &lt;chr&gt;            &lt;date&gt;     &lt;chr&gt;                         &lt;dbl&gt;
## 1 Belleville CAN              1980-05-04 ON                              135
## 2 Riga       LVA              1967-02-02 &lt;NA&gt;                            196
## 3 Toronto    CAN              1965-01-14 ON                               69
## 4 Farmington USA              1977-03-12 MI                              129
## 5 Woonsocket USA              1977-01-02 RI                               22
## 6 Sussex     GBR              1971-02-25 &lt;NA&gt;                             35
## # ℹ 29 more variables: draftRound &lt;dbl&gt;, draftYear &lt;dbl&gt;, fullName &lt;chr&gt;,
## #   height &lt;dbl&gt;, isInHallOfFameYn &lt;chr&gt;, lastName &lt;chr&gt;,
## #   nationalityCode &lt;chr&gt;, playerId &lt;dbl&gt;, catches &lt;chr&gt;, weight &lt;dbl&gt;,
## #   seasonId &lt;dbl&gt;, assists &lt;dbl&gt;, gamesPlayed &lt;dbl&gt;, gamesStarted &lt;dbl&gt;,
## #   goals &lt;dbl&gt;, goalsAgainst &lt;dbl&gt;, goalsAgainstAverage &lt;dbl&gt;, losses &lt;dbl&gt;,
## #   otLosses &lt;dbl&gt;, penaltyMinutes &lt;dbl&gt;, points &lt;dbl&gt;, savePct &lt;dbl&gt;,
## #   saves &lt;dbl&gt;, shotsAgainst &lt;dbl&gt;, shutouts &lt;dbl&gt;, teamAbbrevs &lt;chr&gt;, …</code></pre>
<pre class="r"><code>tail(goalies)</code></pre>
<pre><code>## # A tibble: 6 × 34
##   birthCity      birthCountryCode birthDate  birthStateProvinceCode draftOverall
##   &lt;chr&gt;          &lt;chr&gt;            &lt;date&gt;     &lt;chr&gt;                         &lt;dbl&gt;
## 1 Surrey         CAN              1995-04-29 BC                               44
## 2 Espoo          FIN              1999-03-09 &lt;NA&gt;                             54
## 3 Helsinki       FIN              1995-02-06 &lt;NA&gt;                             94
## 4 Havlickuv Brod CZE              1996-01-09 &lt;NA&gt;                             39
## 5 Dollard-des-O… CAN              2000-03-04 QC                               NA
## 6 Omsk           RUS              2002-06-16 &lt;NA&gt;                             11
## # ℹ 29 more variables: draftRound &lt;dbl&gt;, draftYear &lt;dbl&gt;, fullName &lt;chr&gt;,
## #   height &lt;dbl&gt;, isInHallOfFameYn &lt;chr&gt;, lastName &lt;chr&gt;,
## #   nationalityCode &lt;chr&gt;, playerId &lt;dbl&gt;, catches &lt;chr&gt;, weight &lt;dbl&gt;,
## #   seasonId &lt;dbl&gt;, assists &lt;dbl&gt;, gamesPlayed &lt;dbl&gt;, gamesStarted &lt;dbl&gt;,
## #   goals &lt;dbl&gt;, goalsAgainst &lt;dbl&gt;, goalsAgainstAverage &lt;dbl&gt;, losses &lt;dbl&gt;,
## #   otLosses &lt;dbl&gt;, penaltyMinutes &lt;dbl&gt;, points &lt;dbl&gt;, savePct &lt;dbl&gt;,
## #   saves &lt;dbl&gt;, shotsAgainst &lt;dbl&gt;, shutouts &lt;dbl&gt;, teamAbbrevs &lt;chr&gt;, …</code></pre>
<pre class="r"><code># Check for import issues with NHL goalie prospects data
dim(prospects)</code></pre>
<pre><code>## [1] 869  15</code></pre>
<pre class="r"><code>head(prospects)</code></pre>
<pre><code>## # A tibble: 6 × 15
##   positionCode catches height weight lastAmateurClub lastAmateurLeague
##   &lt;chr&gt;        &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;           &lt;chr&gt;            
## 1 G            L           78    196 Brynas Jr.      SWEDEN-JR.       
## 2 G            L           74    220 Guelph          OHL              
## 3 G            L           74    215 Tri-City        WHL              
## 4 G            L           73    202 Tappara         FINLAND          
## 5 G            L           74    185 Lewiston        QMJHL            
## 6 G            L           78    220 Brynas          SWEDEN           
## # ℹ 9 more variables: birthDate &lt;date&gt;, birthCity &lt;chr&gt;,
## #   birthStateProvince &lt;chr&gt;, birthCountryCode &lt;chr&gt;, midtermRank &lt;dbl&gt;,
## #   finalRank &lt;dbl&gt;, draftYear &lt;dbl&gt;, international &lt;lgl&gt;, fullName &lt;chr&gt;</code></pre>
<pre class="r"><code>tail(prospects)</code></pre>
<pre><code>## # A tibble: 6 × 15
##   positionCode catches height weight lastAmateurClub lastAmateurLeague
##   &lt;chr&gt;        &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;           &lt;chr&gt;            
## 1 G            L           74    172 BURLINGTON      OJHL             
## 2 G            L           73    185 USA U-18        NTDP - USHL      
## 3 G            R           72    176 WATERLOO        USHL             
## 4 G            L           74    172 BRUNSWICK PREP  HIGH-CT          
## 5 G            L           74    180 BRANTFORD       OHL              
## 6 G            L           76    182 RIMOUSKI        QMJHL            
## # ℹ 9 more variables: birthDate &lt;date&gt;, birthCity &lt;chr&gt;,
## #   birthStateProvince &lt;chr&gt;, birthCountryCode &lt;chr&gt;, midtermRank &lt;dbl&gt;,
## #   finalRank &lt;dbl&gt;, draftYear &lt;dbl&gt;, international &lt;lgl&gt;, fullName &lt;chr&gt;</code></pre>
<p>Integer columns are being imported as doubles so I will explicitly
set the types for these columns. We could also convert some of the
character columns to factors. There doesn’t appear to be any import
errors otherwise. We have 2256 rows across 34 variables for the NHL
goalies by season data and 869 rows across 15 variables for the NHL
goalie prospects by draft year data.</p>
<pre class="r"><code># Convert the invalid double columns in the goalies data to integers and create some factors
goalies = goalies |&gt;
  mutate(
    across(
      c(seasonId, playerId, height, weight, draftYear, draftRound, draftOverall, assists, 
        gamesPlayed, gamesStarted, goals, goalsAgainst, losses, otLosses, penaltyMinutes,
        points, saves, shotsAgainst, shutouts, ties, timeOnIce, wins),
      as.integer
    ),
    across(
      c(birthCountryCode, isInHallOfFameYn, catches),
      as.factor
    )
  )</code></pre>
<pre class="r"><code># Convert the invalid double columns in the prospects data to integers and create some factors
prospects = prospects |&gt;
  mutate(
    across(
      c(draftYear, height, weight, midtermRank, finalRank),
      as.integer
    ),
    across(
      c(positionCode, catches, birthCountryCode),
      as.factor
    )
  )</code></pre>
<pre class="r"><code># Check the variable types in the goalies data
str(goalies)</code></pre>
<pre><code>## tibble [2,256 × 34] (S3: tbl_df/tbl/data.frame)
##  $ birthCity             : chr [1:2256] &quot;Belleville&quot; &quot;Riga&quot; &quot;Toronto&quot; &quot;Farmington&quot; ...
##  $ birthCountryCode      : Factor w/ 19 levels &quot;AUT&quot;,&quot;BGR&quot;,&quot;BLR&quot;,..: 4 14 4 18 18 11 4 4 18 4 ...
##  $ birthDate             : Date[1:2256], format: &quot;1980-05-04&quot; &quot;1967-02-02&quot; ...
##  $ birthStateProvinceCode: chr [1:2256] &quot;ON&quot; NA &quot;ON&quot; &quot;MI&quot; ...
##  $ draftOverall          : int [1:2256] 135 196 69 129 22 35 122 54 85 169 ...
##  $ draftRound            : int [1:2256] 5 10 4 5 1 2 5 3 5 8 ...
##  $ draftYear             : int [1:2256] 1998 1989 1983 1995 1995 1989 1995 1991 1983 1991 ...
##  $ fullName              : chr [1:2256] &quot;Andrew Raycroft&quot; &quot;Arturs Irbe&quot; &quot;Bob Essensa&quot; &quot;Brent Johnson&quot; ...
##  $ height                : int [1:2256] 73 68 72 75 74 71 72 70 69 70 ...
##  $ isInHallOfFameYn      : Factor w/ 2 levels &quot;N&quot;,&quot;Y&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ lastName              : chr [1:2256] &quot;Raycroft&quot; &quot;Irbe&quot; &quot;Essensa&quot; &quot;Johnson&quot; ...
##  $ nationalityCode       : chr [1:2256] &quot;CAN&quot; &quot;LVA&quot; &quot;CAN&quot; &quot;USA&quot; ...
##  $ playerId              : int [1:2256] 8467453 8456692 8446719 8462161 8462052 8455994 8462152 8458568 8451860 8458680 ...
##  $ catches               : Factor w/ 2 levels &quot;L&quot;,&quot;R&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ weight                : int [1:2256] 180 190 188 199 200 185 198 180 170 170 ...
##  $ seasonId              : int [1:2256] 20002001 20002001 20002001 20002001 20002001 20002001 20002001 20002001 20002001 20002001 ...
##  $ assists               : int [1:2256] 0 2 0 0 0 2 0 0 0 0 ...
##  $ gamesPlayed           : int [1:2256] 15 83 41 33 28 45 1 58 18 1 ...
##  $ gamesStarted          : int [1:2256] 11 82 35 30 24 45 1 54 13 0 ...
##  $ goals                 : int [1:2256] 0 0 0 0 0 0 0 0 0 0 ...
##  $ goalsAgainst          : int [1:2256] 32 200 98 65 83 101 2 142 39 0 ...
##  $ goalsAgainstAverage   : num [1:2256] 2.96 2.52 2.7 2.16 3.31 ...
##  $ losses                : int [1:2256] 6 33 14 10 12 14 1 23 9 0 ...
##  $ otLosses              : int [1:2256] NA NA NA NA NA NA NA NA NA NA ...
##  $ penaltyMinutes        : int [1:2256] 0 10 4 2 2 6 0 8 2 0 ...
##  $ points                : int [1:2256] 0 2 0 0 0 2 0 0 0 0 ...
##  $ savePct               : num [1:2256] 0.89 0.907 0.893 0.909 0.874 ...
##  $ saves                 : int [1:2256] 259 1948 814 647 578 975 18 1326 333 8 ...
##  $ shotsAgainst          : int [1:2256] 291 2148 912 712 661 1076 20 1468 372 8 ...
##  $ shutouts              : int [1:2256] 0 6 1 4 1 2 0 2 0 0 ...
##  $ teamAbbrevs           : chr [1:2256] &quot;BOS&quot; &quot;CAR&quot; &quot;VAN&quot; &quot;STL&quot; ...
##  $ ties                  : int [1:2256] 0 9 3 2 5 7 0 4 2 0 ...
##  $ timeOnIce             : int [1:2256] 38918 285923 130849 108350 90373 152188 3515 191941 53761 1200 ...
##  $ wins                  : int [1:2256] 4 39 18 19 8 22 0 27 4 1 ...</code></pre>
<pre class="r"><code># Check OT losses column
summary(goalies$otLosses)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   0.000   0.000   2.000   2.912   5.000  14.000     389</code></pre>
<pre class="r"><code># Check the variable types in the prospects data
str(prospects)</code></pre>
<pre><code>## tibble [869 × 15] (S3: tbl_df/tbl/data.frame)
##  $ positionCode      : Factor w/ 1 level &quot;G&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ catches           : Factor w/ 2 levels &quot;L&quot;,&quot;R&quot;: 1 1 1 1 1 1 1 2 1 1 ...
##  $ height            : int [1:869] 78 74 74 73 74 78 73 74 74 74 ...
##  $ weight            : int [1:869] 196 220 215 202 185 220 200 183 190 186 ...
##  $ lastAmateurClub   : chr [1:869] &quot;Brynas Jr.&quot; &quot;Guelph&quot; &quot;Tri-City&quot; &quot;Tappara&quot; ...
##  $ lastAmateurLeague : chr [1:869] &quot;SWEDEN-JR.&quot; &quot;OHL&quot; &quot;WHL&quot; &quot;FINLAND&quot; ...
##  $ birthDate         : Date[1:869], format: &quot;1990-01-31&quot; &quot;1989-12-07&quot; ...
##  $ birthCity         : chr [1:869] &quot;Gavle&quot; &quot;Amherst&quot; &quot;Moncton&quot; &quot;Toijala&quot; ...
##  $ birthStateProvince: chr [1:869] NA &quot;NY&quot; &quot;NB&quot; NA ...
##  $ birthCountryCode  : Factor w/ 18 levels &quot;BEL&quot;,&quot;BLR&quot;,&quot;CAN&quot;,..: 17 18 3 9 3 17 3 3 14 3 ...
##  $ midtermRank       : int [1:869] 2 3 1 NA 2 NA 9 18 NA NA ...
##  $ finalRank         : int [1:869] 1 1 2 2 3 3 4 5 5 6 ...
##  $ draftYear         : int [1:869] 2008 2008 2008 2008 2008 2008 2008 2008 2008 2008 ...
##  $ international     : logi [1:869] TRUE FALSE FALSE TRUE FALSE TRUE ...
##  $ fullName          : chr [1:869] &quot;Jacob Markstrom&quot; &quot;Thomas McCollum&quot; &quot;Chet Pickard&quot; &quot;Harri Sateri&quot; ...</code></pre>
<p>We fixed issues with integers being cast as doubles. There appear to
be a lot of NA’s in OT losses column for goalies but that’s okay since
we won’t use it anyways. There don’t appear to be any other major issues
at the surface level other than that.</p>
</div>
<div id="data-manipulation" class="section level2">
<h2>Data Manipulation</h2>
<pre class="r"><code># Create column for checking whether a goalie was drafted or not
goalies = goalies |&gt;
  mutate(
    drafted = !is.na(draftYear)
  )

class(goalies$drafted)</code></pre>
<pre><code>## [1] &quot;logical&quot;</code></pre>
<pre class="r"><code>table(goalies$drafted)</code></pre>
<pre><code>## 
## FALSE  TRUE 
##   377  1879</code></pre>
<pre class="r"><code># Create column for goalie age as of the beginning of the season (i.e. September 15th as per NHL Hockey Operations Guidelines)
goalies = goalies |&gt;
  separate(seasonId, into = c(&quot;seasonStartYear&quot;, &quot;seasonEndYear&quot;), sep = 4,
           convert = T, remove = F) |&gt;
  mutate(
    ageAtSeasonStart = as.integer(
      interval(birthDate, date(paste0(seasonStartYear, &quot;-09-15&quot;))) / years()
    )
  )

class(goalies$ageAtSeasonStart)</code></pre>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<pre class="r"><code>summary(goalies$ageAtSeasonStart)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   18.00   24.00   27.00   27.56   31.00   42.00</code></pre>
<pre class="r"><code># Get the average goalie height minus 2 inches for every season
undersize_heights_per_season = goalies |&gt;
  group_by(seasonId) |&gt;
  summarize(
    undersize_threshold = mean(height) - 2
  ) |&gt;
  ungroup()

# Create column classifying a goalie as undersized or not (i.e. &lt;= 2&quot; below average)
goalies = goalies |&gt;
  left_join(undersize_heights_per_season, by = &quot;seasonId&quot;) |&gt;
  mutate(
    undersized = height &lt;= undersize_threshold
  )

# View the effective threshold for being undersized each season
goalies |&gt;
  filter(undersized) |&gt;
  group_by(seasonId) |&gt;
  summarize(
    effective_undersize_threshold = max(height)
  )</code></pre>
<pre><code>## # A tibble: 24 × 2
##    seasonId effective_undersize_threshold
##       &lt;int&gt;                         &lt;int&gt;
##  1 20002001                            70
##  2 20012002                            70
##  3 20022003                            70
##  4 20032004                            71
##  5 20052006                            71
##  6 20062007                            71
##  7 20072008                            71
##  8 20082009                            71
##  9 20092010                            71
## 10 20102011                            71
## # ℹ 14 more rows</code></pre>
<pre class="r"><code>class(goalies$undersized)</code></pre>
<pre><code>## [1] &quot;logical&quot;</code></pre>
<pre class="r"><code>table(goalies$undersized)</code></pre>
<pre><code>## 
## FALSE  TRUE 
##  1940   316</code></pre>
<pre class="r"><code># Order goalies columns to view most important columns first
goalies = goalies |&gt;
  relocate(
    seasonId, playerId, fullName, birthCountryCode, height, gamesPlayed, wins,
    savePct, goalsAgainstAverage, shotsAgainst, saves, goalsAgainst
  )</code></pre>
<pre class="r"><code># Create column for prospect age as of the start of the next season (i.e. September 15th as per NHL Hockey Operations Guidelines)
prospects = prospects |&gt;
  mutate(
    draftYearAge = as.integer(
      interval(birthDate, date(paste0(draftYear, &quot;-09-15&quot;))) / years()
    )
  )

class(prospects$draftYearAge)</code></pre>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<pre class="r"><code>summary(prospects$draftYearAge)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   18.00   18.00   18.00   18.38   19.00   21.00</code></pre>
<pre class="r"><code># Order prospects columns to view most important columns first
prospects = prospects |&gt;
  relocate(
    draftYear, fullName, birthCountryCode, international, height, midtermRank, finalRank
  )</code></pre>
<p>Adding the extra variables will help check the validity of the data
with respect to draft years, birth dates, and height classification.</p>
</div>
<div id="variable-inspection" class="section level2">
<h2>Variable Inspection</h2>
<pre class="r"><code># Summarize the goalies data
summary(goalies)</code></pre>
<pre><code>##     seasonId           playerId         fullName         birthCountryCode
##  Min.   :20002001   Min.   :8445275   Length:2256        CAN    :987     
##  1st Qu.:20072008   1st Qu.:8467453   Class :character   USA    :442     
##  Median :20132014   Median :8471679   Mode  :character   FIN    :208     
##  Mean   :20128246   Mean   :8470700                      SWE    :183     
##  3rd Qu.:20192020   3rd Qu.:8476343                      CZE    :121     
##  Max.   :20242025   Max.   :8484312                      RUS    :108     
##                                                          (Other):207     
##      height       gamesPlayed         wins          savePct      
##  Min.   :67.00   Min.   : 1.00   Min.   : 0.00   Min.   :0.5000  
##  1st Qu.:73.00   1st Qu.: 7.00   1st Qu.: 2.00   1st Qu.:0.8930  
##  Median :74.00   Median :25.00   Median :10.00   Median :0.9069  
##  Mean   :73.93   Mean   :29.25   Mean   :13.32   Mean   :0.9010  
##  3rd Qu.:75.00   3rd Qu.:47.00   3rd Qu.:21.00   3rd Qu.:0.9169  
##  Max.   :79.00   Max.   :97.00   Max.   :57.00   Max.   :1.0000  
##                                                  NA&#39;s   :7       
##  goalsAgainstAverage  shotsAgainst        saves         goalsAgainst   
##  Min.   : 0.000      Min.   :   0.0   Min.   :   0.0   Min.   :  0.00  
##  1st Qu.: 2.420      1st Qu.: 178.0   1st Qu.: 160.5   1st Qu.: 18.00  
##  Median : 2.766      Median : 658.5   Median : 593.0   Median : 63.00  
##  Mean   : 2.882      Mean   : 810.4   Mean   : 737.0   Mean   : 73.38  
##  3rd Qu.: 3.177      3rd Qu.:1311.5   3rd Qu.:1190.2   3rd Qu.:120.00  
##  Max.   :27.273      Max.   :2668.0   Max.   :2497.0   Max.   :234.00  
##                                                                        
##   birthCity           birthDate          birthStateProvinceCode
##  Length:2256        Min.   :1962-08-23   Length:2256           
##  Class :character   1st Qu.:1978-05-24   Class :character      
##  Mode  :character   Median :1986-01-21   Mode  :character      
##                     Mean   :1985-04-20                         
##                     3rd Qu.:1992-02-14                         
##                     Max.   :2004-03-14                         
##                                                                
##   draftOverall      draftRound      draftYear    isInHallOfFameYn
##  Min.   :  1.00   Min.   : 1.00   Min.   :1981   N:2190          
##  1st Qu.: 37.00   1st Qu.: 2.00   1st Qu.:1997   Y:  66          
##  Median : 77.00   Median : 3.00   Median :2004                   
##  Mean   : 95.49   Mean   : 3.79   Mean   :2003                   
##  3rd Qu.:141.00   3rd Qu.: 5.00   3rd Qu.:2010                   
##  Max.   :291.00   Max.   :11.00   Max.   :2022                   
##  NA&#39;s   :377      NA&#39;s   :377     NA&#39;s   :377                    
##    lastName         nationalityCode    catches      weight      seasonStartYear
##  Length:2256        Length:2256        L:2080   Min.   :146.0   Min.   :2000   
##  Class :character   Class :character   R: 176   1st Qu.:188.0   1st Qu.:2007   
##  Mode  :character   Mode  :character            Median :200.0   Median :2013   
##                                                 Mean   :199.5   Mean   :2013   
##                                                 3rd Qu.:210.0   3rd Qu.:2019   
##                                                 Max.   :250.0   Max.   :2024   
##                                                                                
##  seasonEndYear     assists        gamesStarted      goals         
##  Min.   :2001   Min.   :0.0000   Min.   : 0.0   Min.   :0.000000  
##  1st Qu.:2008   1st Qu.:0.0000   1st Qu.: 6.0   1st Qu.:0.000000  
##  Median :2014   Median :0.0000   Median :22.0   Median :0.000000  
##  Mean   :2014   Mean   :0.6028   Mean   :27.2   Mean   :0.005762  
##  3rd Qu.:2020   3rd Qu.:1.0000   3rd Qu.:44.0   3rd Qu.:0.000000  
##  Max.   :2025   Max.   :8.0000   Max.   :97.0   Max.   :1.000000  
##                                                                   
##      losses         otLosses      penaltyMinutes       points      
##  Min.   : 0.00   Min.   : 0.000   Min.   : 0.000   Min.   :0.0000  
##  1st Qu.: 3.00   1st Qu.: 0.000   1st Qu.: 0.000   1st Qu.:0.0000  
##  Median : 9.00   Median : 2.000   Median : 0.000   Median :0.0000  
##  Mean   :10.91   Mean   : 2.912   Mean   : 2.408   Mean   :0.6086  
##  3rd Qu.:17.00   3rd Qu.: 5.000   3rd Qu.: 2.000   3rd Qu.:1.0000  
##  Max.   :42.00   Max.   :14.000   Max.   :39.000   Max.   :8.0000  
##                  NA&#39;s   :389                                       
##     shutouts      teamAbbrevs             ties          timeOnIce     
##  Min.   : 0.000   Length:2256        Min.   : 0.000   Min.   :     8  
##  1st Qu.: 0.000   Class :character   1st Qu.: 0.000   1st Qu.: 21650  
##  Median : 1.000   Mode  :character   Median : 2.000   Median : 80926  
##  Mean   : 1.737                      Mean   : 3.385   Mean   : 98797  
##  3rd Qu.: 3.000                      3rd Qu.: 6.000   3rd Qu.:157964  
##  Max.   :16.000                      Max.   :14.000   Max.   :351895  
##                                      NA&#39;s   :1885                     
##   drafted        ageAtSeasonStart undersize_threshold undersized     
##  Mode :logical   Min.   :18.00    Min.   :70.41       Mode :logical  
##  FALSE:377       1st Qu.:24.00    1st Qu.:71.26       FALSE:1940     
##  TRUE :1879      Median :27.00    Median :72.17       TRUE :316      
##                  Mean   :27.56    Mean   :71.93                      
##                  3rd Qu.:31.00    3rd Qu.:72.57                      
##                  Max.   :42.00    Max.   :73.03                      
## </code></pre>
<p>It appears most variables in the goalies data have reasonable values,
although there are some potential issues (i.e. with height, time on ice,
and save percentage):</p>
<ul>
<li><p>The age range of 18-42 years old makes sense given that NHL
players need to be at least 18 years old and many stop playing before
their forties (although some do - the oldest active NHL goalie is
40).</p></li>
<li><p>The heights of goalies ranges from 67-79 inches or 5’7”-6’7”.
This is a reasonable range, although I will have to confirm 5’7” is
accurate given this is considered extremely undersized for an NHL
goalie.</p></li>
<li><p>There are 377 NA’s in each of the draft variables. This makes
sense given that you can make the NHL without being selected in the NHL
Entry Draft (although it is definitely more rare). For further comfort,
each of <code>draftYear</code>, <code>draftRound</code>, and
<code>draftOverall</code> have exactly the same number of NA’s which is
a good sign that <code>drafted</code> is encoded properly since being
undrafted means all 3 of these variables should be empty.</p></li>
<li><p>The maximum number of games that can be played in a single season
(including regular season and playoffs) is 110 so the range of 1-97 for
games played and 0-57 for wins makes sense, further validating the
data.</p></li>
<li><p>Goals against average (GAA) appears to have a reasonable range,
although there is definitely a point of interest with the value 27.273
(this is extremely high, although possible due to how GAA is
calculated).</p></li>
<li><p>Time on ice (measured in seconds) indicates that someone only
played 8 seconds in an entire season. This likely indicates an emergency
backup situation or something similar and thus, needs
investigation.</p></li>
<li><p>Save percentage (SV%) has 7 missing values. This could indicate a
goalie who faced 0 shots, likely indicating an emergency backup
situation. This also needs further investigation.</p></li>
</ul>
<pre class="r"><code># Investigate 5&#39;7&quot; goalie (and other goalies under 5&#39;10&quot; = 70&quot;)
goalies |&gt;
  filter(height &lt; 70) |&gt;
  select(seasonId, fullName, height) |&gt;
  arrange(height, fullName, seasonId)</code></pre>
<pre><code>## # A tibble: 27 × 3
##    seasonId fullName        height
##       &lt;int&gt; &lt;chr&gt;            &lt;int&gt;
##  1 20002001 Fred Brathwaite     67
##  2 20012002 Fred Brathwaite     67
##  3 20022003 Fred Brathwaite     67
##  4 20032004 Fred Brathwaite     67
##  5 20112012 Shawn Hunwick       67
##  6 20002001 Arturs Irbe         68
##  7 20012002 Arturs Irbe         68
##  8 20022003 Arturs Irbe         68
##  9 20032004 Arturs Irbe         68
## 10 20002001 Glenn Healy         68
## # ℹ 17 more rows</code></pre>
<p>After verifying these goalies with external sources, all of their
heights are valid.</p>
<pre class="r"><code># Investigate missing save percentages
goalies |&gt;
  filter(is.na(savePct)) |&gt;
  relocate(seasonId, fullName, savePct, shotsAgainst, timeOnIce) |&gt;
  arrange(seasonId, fullName)</code></pre>
<pre><code>## # A tibble: 7 × 40
##   seasonId fullName     savePct shotsAgainst timeOnIce playerId birthCountryCode
##      &lt;int&gt; &lt;chr&gt;          &lt;dbl&gt;        &lt;int&gt;     &lt;int&gt;    &lt;int&gt; &lt;fct&gt;           
## 1 20002001 Evgeny Kons…      NA            0        24  8467940 RUS             
## 2 20052006 Jordan Siga…      NA            0        43  8469653 CAN             
## 3 20052006 Robert McVi…      NA            0       164  8469750 CAN             
## 4 20112012 Jake Allen        NA            0        67  8474596 CAN             
## 5 20112012 Shawn Hunwi…      NA            0       153  8476803 USA             
## 6 20162017 Jorge Alves       NA            0         8  8479115 USA             
## 7 20222023 Jett Alexan…      NA            0        70  8483183 CAN             
## # ℹ 33 more variables: height &lt;int&gt;, gamesPlayed &lt;int&gt;, wins &lt;int&gt;,
## #   goalsAgainstAverage &lt;dbl&gt;, saves &lt;int&gt;, goalsAgainst &lt;int&gt;,
## #   birthCity &lt;chr&gt;, birthDate &lt;date&gt;, birthStateProvinceCode &lt;chr&gt;,
## #   draftOverall &lt;int&gt;, draftRound &lt;int&gt;, draftYear &lt;int&gt;,
## #   isInHallOfFameYn &lt;fct&gt;, lastName &lt;chr&gt;, nationalityCode &lt;chr&gt;,
## #   catches &lt;fct&gt;, weight &lt;int&gt;, seasonStartYear &lt;int&gt;, seasonEndYear &lt;int&gt;,
## #   assists &lt;int&gt;, gamesStarted &lt;int&gt;, goals &lt;int&gt;, losses &lt;int&gt;, …</code></pre>
<p>After investigating the 7 observations with missing save percentages,
I found the following:</p>
<ul>
<li><p>Evgeny Konstantinov was a goalie drafted by Tampa Bay but only
appeared in 2 NHL games throughout his career. There is no indication,
however, that this was an emergency backup situation.</p></li>
<li><p>Jordan Sigalet was a professional goalie whose career was cut
short due to his battle with MS. He played many games in the AHL,
indicating his one game in the NHL was due to skill rather than an
emergency scenerio.</p></li>
<li><p>Robert McVicar was a professional goalie who was called up a
dozen or so times during the 2005-2006 season. While he never faced a
shot, he was on the team based off merit.</p></li>
<li><p>Jake Allen is a current goalie in the NHL and has been for over a
decade.</p></li>
<li><p>Shawn Hunwick was an emergency backup for a couple of days in
2012 when Columbus was facing sudden injury problems (hence the 2:33 of
ice time).</p></li>
<li><p>Jorge Alves was an equipment manager for Carolina and also backed
up for one game due to emergency injury trouble.</p></li>
<li><p>Jett Alexander was an emergency backup for one game with Toronto
due to injury troubles on the team. The coach put him in for the last 70
seconds of a game they were winning 7-1. As a fun aside, I played with
Jett that year and was in the stands for this game as an emergency
backup.</p></li>
</ul>
<p>I don’t want to keep goalies in the data that only played once and
never again due to emergency scenerios. This is because in emergency
situations teams usually grab the goalie who is most available, rather
than picking a goalie from their system or farm team that is the next
best in line. Keeping these observations would take away from the
quality of my analysis so my objective is to rid them where possible.
Therefore, I will remove the 3 observations deemed as emergency backups.
It should be noted that there are only 6 times an emergency backup has
played, so I will manually identify and remove the rest of these
observations as well.</p>
<pre class="r"><code># Find emergency situation goalies
emergency_goalies = goalies |&gt;
  filter (fullName %in% c(&quot;Shawn Hunwick&quot;, &quot;Jorge Alves&quot;, &quot;Jett Alexander&quot;,
                          &quot;Thomas Hodges&quot;, &quot;Matthew Berlin&quot;, &quot;Scott Foster&quot;))

emergency_goalies</code></pre>
<pre><code>## # A tibble: 6 × 40
##   seasonId playerId fullName   birthCountryCode height gamesPlayed  wins savePct
##      &lt;int&gt;    &lt;int&gt; &lt;chr&gt;      &lt;fct&gt;             &lt;int&gt;       &lt;int&gt; &lt;int&gt;   &lt;dbl&gt;
## 1 20112012  8476803 Shawn Hun… USA                  67           1     0  NA    
## 2 20162017  8479115 Jorge Alv… USA                  69           1     0  NA    
## 3 20172018  8479138 Scott Fos… CAN                  72           1     0   1    
## 4 20212022  8480591 Thomas Ho… GBR                  70           1     0   0.667
## 5 20222023  8483183 Jett Alex… CAN                  77           1     0  NA    
## 6 20222023  8483158 Matthew B… CAN                  75           1     0   1    
## # ℹ 32 more variables: goalsAgainstAverage &lt;dbl&gt;, shotsAgainst &lt;int&gt;,
## #   saves &lt;int&gt;, goalsAgainst &lt;int&gt;, birthCity &lt;chr&gt;, birthDate &lt;date&gt;,
## #   birthStateProvinceCode &lt;chr&gt;, draftOverall &lt;int&gt;, draftRound &lt;int&gt;,
## #   draftYear &lt;int&gt;, isInHallOfFameYn &lt;fct&gt;, lastName &lt;chr&gt;,
## #   nationalityCode &lt;chr&gt;, catches &lt;fct&gt;, weight &lt;int&gt;, seasonStartYear &lt;int&gt;,
## #   seasonEndYear &lt;int&gt;, assists &lt;int&gt;, gamesStarted &lt;int&gt;, goals &lt;int&gt;,
## #   losses &lt;int&gt;, otLosses &lt;int&gt;, penaltyMinutes &lt;int&gt;, points &lt;int&gt;, …</code></pre>
<pre class="r"><code># Remove emergency goalies from data
goalies = goalies |&gt;
  anti_join(emergency_goalies, by = &quot;playerId&quot;)

nrow(goalies)</code></pre>
<pre><code>## [1] 2250</code></pre>
<pre class="r"><code># Investigate limited time on ice
summary(goalies$timeOnIce)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##      24   21832   81109   99060  158218  351895</code></pre>
<pre class="r"><code># Investigate the goalies who played less than a minute
goalies |&gt;
  filter(timeOnIce &lt; 60)</code></pre>
<pre><code>## # A tibble: 2 × 40
##   seasonId playerId fullName   birthCountryCode height gamesPlayed  wins savePct
##      &lt;int&gt;    &lt;int&gt; &lt;chr&gt;      &lt;fct&gt;             &lt;int&gt;       &lt;int&gt; &lt;int&gt;   &lt;dbl&gt;
## 1 20002001  8467940 Evgeny Ko… RUS                  72           1     0      NA
## 2 20052006  8469653 Jordan Si… CAN                  73           1     0      NA
## # ℹ 32 more variables: goalsAgainstAverage &lt;dbl&gt;, shotsAgainst &lt;int&gt;,
## #   saves &lt;int&gt;, goalsAgainst &lt;int&gt;, birthCity &lt;chr&gt;, birthDate &lt;date&gt;,
## #   birthStateProvinceCode &lt;chr&gt;, draftOverall &lt;int&gt;, draftRound &lt;int&gt;,
## #   draftYear &lt;int&gt;, isInHallOfFameYn &lt;fct&gt;, lastName &lt;chr&gt;,
## #   nationalityCode &lt;chr&gt;, catches &lt;fct&gt;, weight &lt;int&gt;, seasonStartYear &lt;int&gt;,
## #   seasonEndYear &lt;int&gt;, assists &lt;int&gt;, gamesStarted &lt;int&gt;, goals &lt;int&gt;,
## #   losses &lt;int&gt;, otLosses &lt;int&gt;, penaltyMinutes &lt;int&gt;, points &lt;int&gt;, …</code></pre>
<p>We have already discussed these goalies. Since we already removed
goalies who played due to emergency circumstances, there is no further
action needed.</p>
<pre class="r"><code># Summarize prospects data
summary(prospects)</code></pre>
<pre><code>##    draftYear      fullName         birthCountryCode international  
##  Min.   :2008   Length:869         CAN    :366      Mode :logical  
##  1st Qu.:2013   Class :character   USA    :198      FALSE:640      
##  Median :2017   Mode  :character   SWE    : 64      TRUE :229      
##  Mean   :2017                      CZE    : 57                     
##  3rd Qu.:2021                      FIN    : 56                     
##  Max.   :2025                      RUS    : 47                     
##                                    (Other): 81                     
##      height      midtermRank       finalRank     positionCode catches
##  Min.   :67.0   Min.   :  1.00   Min.   : 1.00   G:869        L:799  
##  1st Qu.:73.0   1st Qu.:  6.00   1st Qu.: 6.00                R: 70  
##  Median :74.0   Median : 12.00   Median :11.00                       
##  Mean   :74.1   Mean   : 15.28   Mean   :13.45                       
##  3rd Qu.:75.0   3rd Qu.: 21.25   3rd Qu.:21.00                       
##  Max.   :80.0   Max.   :999.00   Max.   :35.00                       
##                 NA&#39;s   :173      NA&#39;s   :162                         
##      weight      lastAmateurClub    lastAmateurLeague    birthDate         
##  Min.   :150.0   Length:869         Length:869         Min.   :1988-01-05  
##  1st Qu.:180.0   Class :character   Class :character   1st Qu.:1994-06-22  
##  Median :190.0   Mode  :character   Mode  :character   Median :1998-10-29  
##  Mean   :190.6                                         Mean   :1998-10-01  
##  3rd Qu.:200.0                                         3rd Qu.:2002-12-20  
##  Max.   :248.0                                         Max.   :2007-09-10  
##                                                                            
##   birthCity         birthStateProvince  draftYearAge  
##  Length:869         Length:869         Min.   :18.00  
##  Class :character   Class :character   1st Qu.:18.00  
##  Mode  :character   Mode  :character   Median :18.00  
##                                        Mean   :18.38  
##                                        3rd Qu.:19.00  
##                                        Max.   :21.00  
## </code></pre>
<pre class="r"><code># Compare number of NAs in final rankings to number of 2025 prospects
prospects |&gt;
  filter(draftYear == 2025) |&gt;
  mutate(total = n()) |&gt;
  select(total, draftYear, midtermRank, finalRank) |&gt;
  summary()</code></pre>
<pre><code>##      total      draftYear     midtermRank      finalRank  
##  Min.   :48   Min.   :2025   Min.   : 1.00   Min.   : NA  
##  1st Qu.:48   1st Qu.:2025   1st Qu.: 6.75   1st Qu.: NA  
##  Median :48   Median :2025   Median :12.50   Median : NA  
##  Mean   :48   Mean   :2025   Mean   :13.83   Mean   :NaN  
##  3rd Qu.:48   3rd Qu.:2025   3rd Qu.:20.25   3rd Qu.: NA  
##  Max.   :48   Max.   :2025   Max.   :32.00   Max.   : NA  
##                                              NA&#39;s   :48</code></pre>
<p>It appears most variables in the prospects data have reasonable
values, although there might be an issue with midterm rank. Notable
thoughts are as follows:</p>
<ul>
<li><p>Draft year has the correct range from 2008 to 2025 as these are
the only years available from the API.</p></li>
<li><p>The heights of prospects are reasonable, ranging from 67 to 80
inches (5’7” to 6’8”).</p></li>
<li><p>Prospects eligible for the NHL Entry Draft must be between 18 and
21 years old by the time the season starts, which is reflected properly
in the <code>draftYearAge</code> variable.</p></li>
<li><p>Mid-season and end-of-season (i.e. midterm and final) rankings
have some missing values. This is expected since the API doesn’t return
a value for goalies who were unranked. Additionally, since the final
season rankings have not been released yet, every final ranking value is
NA for the year 2025.</p></li>
<li><p>Midterm rank has an unusual max of 999. This needs investigation
as most of the time only 30ish goalies are ranked for each of North
American and International categories.</p></li>
</ul>
<pre class="r"><code># Investigate midterm rank of 999
prospects |&gt;
  filter(midtermRank &gt; 50)</code></pre>
<pre><code>## # A tibble: 1 × 16
##   draftYear fullName birthCountryCode international height midtermRank finalRank
##       &lt;int&gt; &lt;chr&gt;    &lt;fct&gt;            &lt;lgl&gt;          &lt;int&gt;       &lt;int&gt;     &lt;int&gt;
## 1      2009 Connor … USA              FALSE             77         999        19
## # ℹ 9 more variables: positionCode &lt;fct&gt;, catches &lt;fct&gt;, weight &lt;int&gt;,
## #   lastAmateurClub &lt;chr&gt;, lastAmateurLeague &lt;chr&gt;, birthDate &lt;date&gt;,
## #   birthCity &lt;chr&gt;, birthStateProvince &lt;chr&gt;, draftYearAge &lt;int&gt;</code></pre>
<p>After further investigation on the official NHL website, the value of
999 likely indicates that scouts only got to view this goalie play a
limited number of times. However, he is still considered unranked at the
time of midterm rankings.</p>
</div>
<div id="summary-statistics-and-visualizations" class="section level2">
<h2>Summary Statistics and Visualizations</h2>
<pre class="r"><code># Explore distribution of goalie heights
goalies |&gt;
  ggplot(aes(height)) +
  geom_histogram(binwidth = 1, color = &quot;black&quot;, fill = &quot;lightblue&quot;) +
  scale_x_continuous(breaks = 67:79) +
  labs(
    title = &quot;Distribution of NHL Goalie Heights Since 2000&quot;,
    x = &quot;Height (in)&quot;,
    y = &quot;Frequency&quot;
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<pre class="r"><code># Get average goalie heights in the NHL over the past 25 years
goalie_heights_per_season = goalies |&gt;
  group_by(seasonStartYear, seasonEndYear) |&gt;
  summarize(
    n = n(),
    min_height = min(height),
    mean_height = mean(height),
    median_height = median(height),
    max_height = max(height)
  ) |&gt;
  ungroup() |&gt;
  arrange(seasonStartYear)</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;seasonStartYear&#39;. You
## can override using the `.groups` argument.</code></pre>
<pre class="r"><code>goalie_heights_per_season</code></pre>
<pre><code>## # A tibble: 24 × 7
##    seasonStartYear seasonEndYear     n min_height mean_height median_height
##              &lt;int&gt;         &lt;int&gt; &lt;int&gt;      &lt;int&gt;       &lt;dbl&gt;         &lt;dbl&gt;
##  1            2000          2001    91         67        72.4            73
##  2            2001          2002    90         67        72.5            73
##  3            2002          2003    94         67        72.7            73
##  4            2003          2004    96         67        73.0            73
##  5            2005          2006    93         70        73.3            73
##  6            2006          2007    84         70        73.2            73
##  7            2007          2008    90         70        73.3            73
##  8            2008          2009    91         70        73.5            73
##  9            2009          2010    84         70        73.5            73
## 10            2010          2011    89         70        73.8            74
## # ℹ 14 more rows
## # ℹ 1 more variable: max_height &lt;int&gt;</code></pre>
<pre class="r"><code># Plot NHL goalie heights over time

# Mean height
goalie_heights_per_season |&gt;
  ggplot(aes(x = seasonStartYear, y = mean_height)) +
  geom_line(color=&quot;lightblue&quot;) +
  geom_point(color=&quot;#000099&quot;) +
  theme_minimal() +
  labs(
    title = &quot;Average Height of NHL Goalies by Season&quot;,
    x = &quot;Season&quot;,
    y = &quot;Average Height&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = &quot;0&quot;), str_pad(seq(1, 25, 2), 2, pad = &quot;0&quot;), sep = &quot;-&quot;)
  ) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<pre class="r"><code># Min height
goalie_heights_per_season |&gt;
  ggplot(aes(x = seasonStartYear, y = min_height)) +
  geom_line(color=&quot;lightblue&quot;) +
  geom_point(color=&quot;#000099&quot;) +
  theme_minimal() +
  labs(
    title = &quot;Minimum Height of NHL Goalies by Season&quot;,
    x = &quot;Season&quot;,
    y = &quot;Minimum Height&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = &quot;0&quot;), str_pad(seq(1, 25, 2), 2, pad = &quot;0&quot;), sep = &quot;-&quot;)
  ) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-30-2.png" width="672" /></p>
<pre class="r"><code># Median height
goalie_heights_per_season |&gt;
  ggplot(aes(x = seasonStartYear, y = median_height)) +
  geom_line(color=&quot;lightblue&quot;) +
  geom_point(color=&quot;#000099&quot;) +
  theme_minimal() +
  labs(
    title = &quot;Median Height of NHL Goalies by Season&quot;,
    x = &quot;Season&quot;,
    y = &quot;Median Height&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = &quot;0&quot;), str_pad(seq(1, 25, 2), 2, pad = &quot;0&quot;), sep = &quot;-&quot;)
  ) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-30-3.png" width="672" /></p>
<pre class="r"><code># Max height
goalie_heights_per_season |&gt;
  ggplot(aes(x = seasonStartYear, y = max_height)) +
  geom_line(color=&quot;lightblue&quot;) +
  geom_point(color=&quot;#000099&quot;) +
  theme_minimal() +
  labs(
    title = &quot;Maximum Height of NHL Goalies by Season&quot;,
    x = &quot;Season&quot;,
    y = &quot;Maximum Height&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = &quot;0&quot;), str_pad(seq(1, 25, 2), 2, pad = &quot;0&quot;), sep = &quot;-&quot;)
  ) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-30-4.png" width="672" /></p>
<pre class="r"><code># Explore correlation between physical attributes and time
goalies |&gt;
  select(seasonStartYear, height, weight) |&gt;
  cor() |&gt;
  ggcorrplot(lab = T, title = &quot;Correlation Between Physical Attributes and\nTime of NHL Goalies&quot;)</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>It appears that NHL goalies have been trending taller over the past
25 years. The mean height has consistently increased from about 72.4
inches to just over 75 inches. Similarly, the minimum height has risen
from 67 inches to 71 inches, median from 73 inches to 75 inches, and
maximum from 76 to 79 inches. It is worth noting that the minimum and
maximum don’t necessarily mean much since there could be one very
small/big goalie who stays in the league for multiple seasons. However,
the upward trend in mean height and moderately strong correlation
coefficient of 0.39 between height and season is indicative of NHL
goalies getting bigger. On top of this, there hasn’t been a goalie under
5’11” in the past 6 seasons.</p>
<pre class="r"><code># Check how many observations are considered established
established_goalies = goalies |&gt;
  filter(gamesPlayed &gt;= 25 | (gamesPlayed &gt;= 22 &amp; seasonStartYear == 2024))

established_goalies |&gt;
  summarize(
    n = n(),
    prop_of_goalies = n() / nrow(goalies),
    prop_of_shots_against = sum(shotsAgainst) / sum(goalies$shotsAgainst),
    prop_of_goals_against = sum(goalsAgainst) / sum(goalies$goalsAgainst),
    prop_of_time_on_ice = sum(timeOnIce) / sum(goalies$timeOnIce)
  )</code></pre>
<pre><code>## # A tibble: 1 × 5
##       n prop_of_goalies prop_of_shots_against prop_of_goals_against
##   &lt;int&gt;           &lt;dbl&gt;                 &lt;dbl&gt;                 &lt;dbl&gt;
## 1  1146           0.509                 0.854                 0.839
## # ℹ 1 more variable: prop_of_time_on_ice &lt;dbl&gt;</code></pre>
<p>Approximately 51% of the goalies data includes “established” goalies
i.e. goalies who played at least 25 games (or 22 for the current 2024-25
season). This threshold comes from the default filter for stat leaders
on NHL.com. Around 85% of the shots faced and 84% of goals allowed in
the NHL since 2000 have been against established goalies. This makes
sense given that established goalies also make up around 85% of the time
played in the data.</p>
<pre class="r"><code># Get average goalie heights of established goalies in the NHL over the past 25 years
established_goalie_heights_per_season = established_goalies |&gt;
  group_by(seasonStartYear, seasonEndYear) |&gt;
  summarize(
    n = n(),
    min_height = min(height),
    mean_height = mean(height),
    median_height = median(height),
    max_height = max(height),
    .groups = &quot;drop&quot;
  ) |&gt;
  ungroup() |&gt;
  arrange(seasonStartYear)

established_goalie_heights_per_season</code></pre>
<pre><code>## # A tibble: 24 × 7
##    seasonStartYear seasonEndYear     n min_height mean_height median_height
##              &lt;int&gt;         &lt;int&gt; &lt;int&gt;      &lt;int&gt;       &lt;dbl&gt;         &lt;dbl&gt;
##  1            2000          2001    48         67        72.4            73
##  2            2001          2002    45         67        72.7            73
##  3            2002          2003    42         67        72.8            73
##  4            2003          2004    45         70        73.0            73
##  5            2005          2006    52         70        73.1            73
##  6            2006          2007    44         70        73              73
##  7            2007          2008    44         70        73.2            73
##  8            2008          2009    47         70        73.2            73
##  9            2009          2010    47         70        73.6            74
## 10            2010          2011    49         71        73.7            74
## # ℹ 14 more rows
## # ℹ 1 more variable: max_height &lt;int&gt;</code></pre>
<pre class="r"><code># Plot NHL goalies heights over time for goalies with at least 25 games played (22 for current season)

# Mean height
established_goalie_heights_per_season |&gt;
  ggplot(aes(x = seasonStartYear, y = mean_height)) +
  geom_line(color=&quot;lightblue&quot;) +
  geom_point(color=&quot;#000099&quot;) +
  theme_minimal() +
  labs(
    title = &quot;Average Height of NHL Goalies by Season (Minimum 25 Games Played)&quot;,
    x = &quot;Season&quot;,
    y = &quot;Average Height&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = &quot;0&quot;), str_pad(seq(1, 25, 2), 2, pad = &quot;0&quot;), sep = &quot;-&quot;)
  ) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<pre class="r"><code># Min height
established_goalie_heights_per_season |&gt;
  ggplot(aes(x = seasonStartYear, y = min_height)) +
  geom_line(color=&quot;lightblue&quot;) +
  geom_point(color=&quot;#000099&quot;) +
  theme_minimal() +
  labs(
    title = &quot;Minimum Height of Established NHL Goalies by Season&quot;,
    x = &quot;Season&quot;,
    y = &quot;Minimum Height&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = &quot;0&quot;), str_pad(seq(1, 25, 2), 2, pad = &quot;0&quot;), sep = &quot;-&quot;)
  ) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-34-2.png" width="672" /></p>
<pre class="r"><code># Median height
established_goalie_heights_per_season |&gt;
  ggplot(aes(x = seasonStartYear, y = median_height)) +
  geom_line(color=&quot;lightblue&quot;) +
  geom_point(color=&quot;#000099&quot;) +
  theme_minimal() +
  labs(
    title = &quot;Median Height of Established NHL Goalies by Season&quot;,
    x = &quot;Season&quot;,
    y = &quot;Median Height&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = &quot;0&quot;), str_pad(seq(1, 25, 2), 2, pad = &quot;0&quot;), sep = &quot;-&quot;)
  ) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-34-3.png" width="672" /></p>
<pre class="r"><code># Max height
established_goalie_heights_per_season |&gt;
  ggplot(aes(x = seasonStartYear, y = max_height)) +
  geom_line(color=&quot;lightblue&quot;) +
  geom_point(color=&quot;#000099&quot;) +
  theme_minimal() +
  labs(
    title = &quot;Maximum Height of Established NHL Goalies by Season&quot;,
    x = &quot;Season&quot;,
    y = &quot;Maximum Height&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = &quot;0&quot;), str_pad(seq(1, 25, 2), 2, pad = &quot;0&quot;), sep = &quot;-&quot;)
  ) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-34-4.png" width="672" /></p>
<p>The results for established goalies follow the same upward trend in
height as all goalies. This means the results seen earlier are not
influenced by call-ups who are only in the league for a couple of
games.</p>
<pre class="r"><code># Get the top 5 NHL goalie producing countries in each season
goalie_counts_by_country_and_season = goalies |&gt;
  group_by(seasonStartYear, seasonEndYear, birthCountryCode) |&gt;
  summarize(n = n(), .groups = &quot;drop_last&quot;) |&gt;
  slice_max(n, n = 5, with_ties = F) |&gt;
  ungroup() |&gt;
  arrange(seasonStartYear, -n)

goalie_counts_by_country_and_season</code></pre>
<pre><code>## # A tibble: 120 × 4
##    seasonStartYear seasonEndYear birthCountryCode     n
##              &lt;int&gt;         &lt;int&gt; &lt;fct&gt;            &lt;int&gt;
##  1            2000          2001 CAN                 55
##  2            2000          2001 USA                 15
##  3            2000          2001 CZE                  5
##  4            2000          2001 FIN                  3
##  5            2000          2001 SWE                  3
##  6            2001          2002 CAN                 52
##  7            2001          2002 USA                 13
##  8            2001          2002 CZE                  6
##  9            2001          2002 FIN                  6
## 10            2001          2002 SWE                  3
## # ℹ 110 more rows</code></pre>
<pre class="r"><code># Plot the top 5 goalie countries
goalie_counts_by_country_and_season |&gt;
  filter(seasonStartYear &gt;= 2005) |&gt;
  ggplot(aes(x = seasonStartYear, y = n, fill = reorder(birthCountryCode, -n))) +
  geom_bar(stat = &quot;identity&quot;, position = &quot;dodge&quot;, width = 0.8) +
  labs(
    title = &quot;Top 5 Birth Countries of NHL Goalies by Season&quot;,
    x = &quot;Season&quot;,
    y = &quot;Count&quot;,
    legend = &quot;Country&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = &quot;0&quot;), str_pad(seq(1, 25, 2), 2, pad = &quot;0&quot;), sep = &quot;-&quot;)
  ) +
  scale_fill_brewer(&quot;Country&quot;, palette = &quot;Set1&quot;)</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<pre class="r"><code># Get average goalie heights in the NHL over the past 25 years by country
goalie_heights_per_season_country = goalies |&gt;
  filter(birthCountryCode %in% c(&quot;CAN&quot;, &quot;USA&quot;, &quot;SWE&quot;, &quot;FIN&quot;)) |&gt;
  group_by(seasonStartYear, seasonEndYear, birthCountryCode) |&gt;
  summarize(
    n = n(),
    min_height = min(height),
    mean_height = mean(height),
    median_height = median(height),
    max_height = max(height),
    .groups = &quot;drop&quot;
  ) |&gt;
  ungroup() |&gt;
  arrange(birthCountryCode, seasonStartYear)

goalie_heights_per_season_country</code></pre>
<pre><code>## # A tibble: 96 × 8
##    seasonStartYear seasonEndYear birthCountryCode     n min_height mean_height
##              &lt;int&gt;         &lt;int&gt; &lt;fct&gt;            &lt;int&gt;      &lt;int&gt;       &lt;dbl&gt;
##  1            2000          2001 CAN                 55         67        72.3
##  2            2001          2002 CAN                 52         67        72.4
##  3            2002          2003 CAN                 53         67        72.6
##  4            2003          2004 CAN                 55         67        73.0
##  5            2005          2006 CAN                 49         70        73.1
##  6            2006          2007 CAN                 43         70        73.2
##  7            2007          2008 CAN                 45         70        73.2
##  8            2008          2009 CAN                 45         70        73.6
##  9            2009          2010 CAN                 42         70        73.7
## 10            2010          2011 CAN                 42         70        73.7
## # ℹ 86 more rows
## # ℹ 2 more variables: median_height &lt;dbl&gt;, max_height &lt;int&gt;</code></pre>
<pre class="r"><code># Plot NHL goalie heights by country over time

# Mean height
goalie_heights_per_season_country |&gt;
  ggplot(aes(x = seasonStartYear, y = mean_height, colour = birthCountryCode)) +
  geom_line() +
  geom_point() +
  facet_wrap(~birthCountryCode) +
  theme_minimal() +
  labs(
    title = &quot;Average Height of NHL Goalies by Season and Birth Country&quot;,
    x = &quot;Season&quot;,
    y = &quot;Average Height&quot;,
    colour = &quot;Country&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 6),
    labels = paste0(&quot;&#39;&quot;, str_pad(seq(0, 24, 6), 2, pad = &quot;0&quot;))
  ) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<pre class="r"><code># Min height
goalie_heights_per_season_country |&gt;
  ggplot(aes(x = seasonStartYear, y = min_height, colour = birthCountryCode)) +
  geom_line() +
  geom_point() +
  facet_wrap(~birthCountryCode) +
  theme_minimal() +
  labs(
    title = &quot;Minimum Height of NHL Goalies by Season and Birth Country&quot;,
    x = &quot;Season&quot;,
    y = &quot;Minimum Height&quot;,
    colour = &quot;Country&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 6),
    labels = paste0(&quot;&#39;&quot;, str_pad(seq(0, 24, 6), 2, pad = &quot;0&quot;))
  ) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-38-2.png" width="672" /></p>
<pre class="r"><code># Median height
goalie_heights_per_season_country |&gt;
  ggplot(aes(x = seasonStartYear, y = median_height, colour = birthCountryCode)) +
  geom_line() +
  geom_point() +
  facet_wrap(~birthCountryCode) +
  theme_minimal() +
  labs(
    title = &quot;Median Height of NHL Goalies by Season and Birth Country&quot;,
    x = &quot;Season&quot;,
    y = &quot;Median Height&quot;,
    colour = &quot;Country&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 6),
    labels = paste0(&quot;&#39;&quot;, str_pad(seq(0, 24, 6), 2, pad = &quot;0&quot;))
  ) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-38-3.png" width="672" /></p>
<pre class="r"><code># Max height
goalie_heights_per_season_country |&gt;
  ggplot(aes(x = seasonStartYear, y = max_height, colour = birthCountryCode)) +
  geom_line() +
  geom_point() +
  facet_wrap(~birthCountryCode) +
  theme_minimal() +
  labs(
    title = &quot;Maximum Height of NHL Goalies by Season and Birth Country&quot;,
    x = &quot;Season&quot;,
    y = &quot;Maximum Height&quot;,
    colour = &quot;Country&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 6),
    labels = paste0(&quot;&#39;&quot;, str_pad(seq(0, 24, 6), 2, pad = &quot;0&quot;))
  ) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-38-4.png" width="672" /></p>
<p>After filtering the data to only include the top 4 NHL goalie
producing countries Canada, United States, Sweden, and Finland, the
upward trend in height is exhibited across all 4 nations. While Canada
and Finland’s averages are currently around 6’3”, the average is
slightly lower for the United States at 6’2.5” and considerably higher
for Sweden just below 6’4.5”.</p>
<pre class="r"><code># Explore distribution of ranked NHL goalie prospects heights
prospects |&gt;
  ggplot(aes(height)) +
  geom_histogram(binwidth = 1, color = &quot;black&quot;, fill = &quot;lightblue&quot;) +
  scale_x_continuous(breaks = 67:79) +
  labs(
    title = &quot;Distribution of Ranked NHL Goalie Prospect Heights Since 2008&quot;,
    x = &quot;Height (in)&quot;,
    y = &quot;Frequency&quot;
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<pre class="r"><code># Get average heights of ranked NHL goalie prospects by draft year
prospect_heights_per_season = prospects |&gt;
  group_by(draftYear) |&gt;
  summarize(
    n = n(),
    min_height = min(height),
    mean_height = mean(height),
    median_height = median(height),
    max_height = max(height)
  ) |&gt;
  ungroup() |&gt;
  arrange(draftYear)

prospect_heights_per_season</code></pre>
<pre><code>## # A tibble: 18 × 6
##    draftYear     n min_height mean_height median_height max_height
##        &lt;int&gt; &lt;int&gt;      &lt;int&gt;       &lt;dbl&gt;         &lt;dbl&gt;      &lt;int&gt;
##  1      2008    25         71        74.1          74           80
##  2      2009    43         71        73.9          74           79
##  3      2010    37         69        73.1          73           77
##  4      2011    48         70        73.8          74           78
##  5      2012    54         70        73.6          74           78
##  6      2013    50         70        73.7          73           78
##  7      2014    56         70        73.9          74           79
##  8      2015    52         70        74.4          74.5         79
##  9      2016    53         72        74.0          74           78
## 10      2017    48         72        74.7          75           79
## 11      2018    56         70        74.4          74           78
## 12      2019    48         71        74.0          74           80
## 13      2020    46         71        74.8          74.5         79
## 14      2021    45         71        74.4          74           79
## 15      2022    52         67        73.8          74           77
## 16      2023    51         72        74.3          74           79
## 17      2024    57         72        74.4          74           79
## 18      2025    48         71        74.4          74           80</code></pre>
<pre class="r"><code># Plot ranked NHL goalie prospects heights over time

# Mean height
prospect_heights_per_season |&gt;
  ggplot(aes(x = draftYear, y = mean_height)) +
  geom_line(color=&quot;lightblue&quot;) +
  geom_point(color=&quot;#000099&quot;) +
  theme_minimal() +
  labs(
    title = &quot;Average Height of Ranked NHL Goalie Prospects by Draft Year&quot;,
    x = &quot;Draft Year&quot;,
    y = &quot;Average Height&quot;
  ) +
  scale_x_continuous(breaks = seq(2008, 2025, 2)) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<pre class="r"><code># Min height
prospect_heights_per_season |&gt;
  ggplot(aes(x = draftYear, y = min_height)) +
  geom_line(color=&quot;lightblue&quot;) +
  geom_point(color=&quot;#000099&quot;) +
  theme_minimal() +
  labs(
    title = &quot;Minimum Height of Ranked NHL Goalie Prospects by Draft Year&quot;,
    x = &quot;Draft Year&quot;,
    y = &quot;Minimum Height&quot;
  ) +
  scale_x_continuous(breaks = seq(2008, 2025, 2)) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-41-2.png" width="672" /></p>
<pre class="r"><code># Median height
prospect_heights_per_season |&gt;
  ggplot(aes(x = draftYear, y = median_height)) +
  geom_line(color=&quot;lightblue&quot;) +
  geom_point(color=&quot;#000099&quot;) +
  theme_minimal() +
  labs(
    title = &quot;Median Height of Ranked NHL Goalie Prospects by Draft Year&quot;,
    x = &quot;Draft Year&quot;,
    y = &quot;Median Height&quot;
  ) +
  scale_x_continuous(breaks = seq(2008, 2025, 2)) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-41-3.png" width="672" /></p>
<pre class="r"><code># Max height
prospect_heights_per_season |&gt;
  ggplot(aes(x = draftYear, y = max_height)) +
  geom_line(color=&quot;lightblue&quot;) +
  geom_point(color=&quot;#000099&quot;) +
  theme_minimal() +
  labs(
    title = &quot;Maximum Height of Ranked NHL Goalie Prospects by Draft Year&quot;,
    x = &quot;Draft Year&quot;,
    y = &quot;Maximum Height&quot;
  ) +
  scale_x_continuous(breaks = seq(2008, 2025, 2)) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-41-4.png" width="672" /></p>
<p>The height of goalie draft prospects appears to stay fairly
consistent. The average height of ranked prospects from 2008 to 2025
tends to stay within the 73.75 to 74.5 inch range without any super
significant trend. This is further validated by the median height which
hovers around 74 inches (6’2”) throughout the same time period. It is
worth noting, however, that the average height is slightly higher in the
last decade compared to the 7 years prior by about 0.5-1 inches.</p>
<pre class="r"><code># Get average heights of ranked NHL goalie prospects by draft year and country
prospect_heights_per_season_and_nation = prospects |&gt;
  mutate(
    nation = as.factor(ifelse(international, &quot;International&quot;, &quot;North American&quot;))
  ) |&gt;
  group_by(draftYear, nation) |&gt;
  summarize(
    n = n(),
    min_height = min(height),
    mean_height = mean(height),
    median_height = median(height),
    max_height = max(height),
    .groups = &quot;drop&quot;
  ) |&gt;
  ungroup() |&gt;
  arrange(nation, draftYear)

prospect_heights_per_season_and_nation</code></pre>
<pre><code>## # A tibble: 36 × 7
##    draftYear nation            n min_height mean_height median_height max_height
##        &lt;int&gt; &lt;fct&gt;         &lt;int&gt;      &lt;int&gt;       &lt;dbl&gt;         &lt;dbl&gt;      &lt;int&gt;
##  1      2008 International     4         73        75.8          76           78
##  2      2009 International    14         71        74.6          75           79
##  3      2010 International     9         69        72.6          73           75
##  4      2011 International    12         70        74.2          74.5         77
##  5      2012 International    13         70        73.3          74           76
##  6      2013 International    10         70        73            72.5         77
##  7      2014 International    15         70        73.7          74           77
##  8      2015 International    11         70        74            74           77
##  9      2016 International    15         72        73.6          74           77
## 10      2017 International    14         72        75            75           79
## # ℹ 26 more rows</code></pre>
<pre class="r"><code># Plot ranked NHL goalie prospects heights over time by nation status

# Mean height
prospect_heights_per_season_and_nation |&gt;
  ggplot(aes(x = draftYear, y = mean_height, colour = nation)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(
    title = &quot;Average Height of Ranked NHL Goalie Prospects\nby Draft Year and International Status&quot;,
    x = &quot;Draft Year&quot;,
    y = &quot;Average Height&quot;,
    colour = &quot;International Status&quot;
  ) +
  scale_x_continuous(breaks = seq(2008, 2025, 2)) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<pre class="r"><code># Min height
prospect_heights_per_season_and_nation |&gt;
  ggplot(aes(x = draftYear, y = min_height, colour = nation)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(
    title = &quot;Minimum Height of Ranked NHL Goalie Prospects\nby Draft Year and International Status&quot;,
    x = &quot;Draft Year&quot;,
    y = &quot;Minimum Height&quot;,
    colour = &quot;International Status&quot;
  ) +
  scale_x_continuous(breaks = seq(2008, 2025, 2)) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-43-2.png" width="672" /></p>
<pre class="r"><code># Median height
prospect_heights_per_season_and_nation |&gt;
  ggplot(aes(x = draftYear, y = median_height, colour = nation)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(
    title = &quot;Median Height of Ranked NHL Goalie Prospects\nby Draft Year and International Status&quot;,
    x = &quot;Draft Year&quot;,
    y = &quot;Median Height&quot;,
    colour = &quot;International Status&quot;
  ) +
  scale_x_continuous(breaks = seq(2008, 2025, 2)) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-43-3.png" width="672" /></p>
<pre class="r"><code># Max height
prospect_heights_per_season_and_nation |&gt;
  ggplot(aes(x = draftYear, y = max_height, colour = nation)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(
    title = &quot;Maximum Height of Ranked NHL Goalie Prospects\nby Draft Year and International Status&quot;,
    x = &quot;Draft Year&quot;,
    y = &quot;Maximum Height&quot;,
    colour = &quot;International Status&quot;
  ) +
  scale_x_continuous(breaks = seq(2008, 2025, 2)) +
  scale_y_continuous(
    breaks = 60:83,
    labels = c(paste0(&quot;5&#39;&quot;, 0:11, &#39;&quot;&#39;), paste0(&quot;6&#39;&quot;, 0:11, &#39;&quot;&#39;))
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-43-4.png" width="672" /></p>
<p>Similar to before, the average height of North American goalie
prospects has stayed close to 6’2” with the same growth trends as the
overall population. International goalies, on the other hand, have
varied between 6’1” and 6’3” over the last 14 years. It is worth noting,
however, that the number of ranked international goalies has been
consistenly less than the North American class, which could explain the
extra variance.</p>
<p>While the trend in average height of goalie prospects has a much
weaker trend (if any) when compared to the goalies who actually played
in the NHL, there is still evidence that NHL goalies have trended taller
over the last quarter decade. This indicates that elite performance
could depend on physical characteristics like height.</p>
<pre class="r"><code># Summarize the SA, GA, SV%, and GAA of established goalies
established_goalies |&gt;
  select(shotsAgainst, goalsAgainst, savePct, goalsAgainstAverage) |&gt;
  summary()</code></pre>
<pre><code>##   shotsAgainst     goalsAgainst       savePct       goalsAgainstAverage
##  Min.   : 457.0   Min.   : 40.00   Min.   :0.8698   Min.   :1.655      
##  1st Qu.: 945.2   1st Qu.: 88.25   1st Qu.:0.9021   1st Qu.:2.385      
##  Median :1298.0   Median :119.00   Median :0.9102   Median :2.653      
##  Mean   :1361.8   Mean   :121.26   Mean   :0.9094   Mean   :2.680      
##  3rd Qu.:1743.8   3rd Qu.:153.00   3rd Qu.:0.9175   3rd Qu.:2.916      
##  Max.   :2668.0   Max.   :234.00   Max.   :0.9388   Max.   :4.230</code></pre>
<pre class="r"><code># Explore distribution of save percentage for established goalies
established_goalies |&gt;
  ggplot(aes(savePct)) +
  geom_histogram(binwidth = 0.003, color = &quot;black&quot;, fill = &quot;lightblue&quot;) +
  scale_x_continuous(breaks = seq(0.800, 1.000, 0.005)) +
  labs(
    title = &quot;Distribution of Save Percentage for Established NHL Goalies Since 2000&quot;,
    x = &quot;Save Percentage&quot;,
    y = &quot;Frequency&quot;
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<pre class="r"><code># Explore distribution of goals against average for established goalies
established_goalies |&gt;
  ggplot(aes(goalsAgainstAverage)) +
  geom_histogram(binwidth = 0.1, color = &quot;black&quot;, fill = &quot;lightblue&quot;) +
  scale_x_continuous(breaks = seq(1, 5, 0.1)) +
  labs(
    title = &quot;Distribution of Goals Against Average for Established NHL Goalies Since 2000&quot;,
    x = &quot;Save Percentage&quot;,
    y = &quot;Frequency&quot;
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-45-2.png" width="672" /></p>
<pre class="r"><code># Calculate the average SV% and GAA across each season
league_stats_by_season = goalies |&gt;
  group_by(seasonStartYear, seasonEndYear) |&gt;
  summarize(
    mean_savePct = sum(saves) / sum(shotsAgainst),
    mean_goalsAgainstAverage = (sum(goalsAgainst) * 60 * 60) / sum(timeOnIce),  # notice secs to mins conversion
    .groups = &quot;drop&quot;
  ) |&gt;
  ungroup() |&gt;
  arrange(seasonStartYear)

league_stats_by_season</code></pre>
<pre><code>## # A tibble: 24 × 4
##    seasonStartYear seasonEndYear mean_savePct mean_goalsAgainstAverage
##              &lt;int&gt;         &lt;int&gt;        &lt;dbl&gt;                    &lt;dbl&gt;
##  1            2000          2001        0.904                     2.62
##  2            2001          2002        0.908                     2.49
##  3            2002          2003        0.909                     2.52
##  4            2003          2004        0.912                     2.43
##  5            2005          2006        0.902                     2.91
##  6            2006          2007        0.906                     2.74
##  7            2007          2008        0.909                     2.60
##  8            2008          2009        0.909                     2.72
##  9            2009          2010        0.911                     2.66
## 10            2010          2011        0.913                     2.61
## # ℹ 14 more rows</code></pre>
<pre class="r"><code># Plot the average league wide save percentage of each season
league_stats_by_season |&gt;
  ggplot(aes(x = seasonStartYear, y = mean_savePct)) +
  geom_line(color=&quot;lightblue&quot;) +
  geom_point(color=&quot;#000099&quot;) +
  theme_minimal() +
  labs(
    title = &quot;Average League-Wide Save Percentage in the NHL by Season&quot;,
    x = &quot;Season&quot;,
    y = &quot;Average Save %&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = &quot;0&quot;), str_pad(seq(1, 25, 2), 2, pad = &quot;0&quot;), sep = &quot;-&quot;)
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<pre class="r"><code># Plot the average league wide GAA of each season
league_stats_by_season |&gt;
  ggplot(aes(x = seasonStartYear, y = mean_goalsAgainstAverage)) +
  geom_line(color=&quot;lightblue&quot;) +
  geom_point(color=&quot;#000099&quot;) +
  theme_minimal() +
  labs(
    title = &quot;Average League-Wide Goals Against Average in the NHL by Season&quot;,
    x = &quot;Season&quot;,
    y = &quot;Average GAA&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = &quot;0&quot;), str_pad(seq(1, 25, 2), 2, pad = &quot;0&quot;), sep = &quot;-&quot;)
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<pre class="r"><code># Calculate the average SV% and GAA across each season for established goalies
established_league_stats_by_season = established_goalies |&gt;
  group_by(seasonStartYear, seasonEndYear) |&gt;
  summarize(
    mean_savePct = sum(saves) / sum(shotsAgainst),
    mean_goalsAgainstAverage = (sum(goalsAgainst) * 60 * 60) / sum(timeOnIce),  # notice secs to mins conversion
    .groups = &quot;drop&quot;
  ) |&gt;
  ungroup() |&gt;
  arrange(seasonStartYear)

established_league_stats_by_season</code></pre>
<pre><code>## # A tibble: 24 × 4
##    seasonStartYear seasonEndYear mean_savePct mean_goalsAgainstAverage
##              &lt;int&gt;         &lt;int&gt;        &lt;dbl&gt;                    &lt;dbl&gt;
##  1            2000          2001        0.906                     2.55
##  2            2001          2002        0.909                     2.46
##  3            2002          2003        0.911                     2.47
##  4            2003          2004        0.914                     2.37
##  5            2005          2006        0.903                     2.87
##  6            2006          2007        0.908                     2.66
##  7            2007          2008        0.911                     2.56
##  8            2008          2009        0.911                     2.67
##  9            2009          2010        0.912                     2.64
## 10            2010          2011        0.914                     2.59
## # ℹ 14 more rows</code></pre>
<pre class="r"><code># Plot the average league wide save percentage of each season for established goalies
established_league_stats_by_season |&gt;
  ggplot(aes(x = seasonStartYear, y = mean_savePct)) +
  geom_line(color=&quot;lightblue&quot;) +
  geom_point(color=&quot;#000099&quot;) +
  theme_minimal() +
  labs(
    title = &quot;Average League-Wide Save Percentage in the NHL\nby Season for Established Goalies&quot;,
    x = &quot;Season&quot;,
    y = &quot;Average Save %&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = &quot;0&quot;), str_pad(seq(1, 25, 2), 2, pad = &quot;0&quot;), sep = &quot;-&quot;)
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
<pre class="r"><code># Plot the average league wide GAA of each season for established goalies
established_league_stats_by_season |&gt;
  ggplot(aes(x = seasonStartYear, y = mean_goalsAgainstAverage)) +
  geom_line(color=&quot;lightblue&quot;) +
  geom_point(color=&quot;#000099&quot;) +
  theme_minimal() +
  labs(
    title = &quot;Average League-Wide Goals Against Average in the NHL\nby Season for Established Goalies&quot;,
    x = &quot;Season&quot;,
    y = &quot;Average GAA&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = &quot;0&quot;), str_pad(seq(1, 25, 2), 2, pad = &quot;0&quot;), sep = &quot;-&quot;)
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<p>League-wide average save percentage has trended downwards since the
2014-15 season (.915 to .901). With a decrease in save percentage, I
would intuitively expect to see an increase in goals against average. As
expected, league-wide goals against average increased from 2.50 in
2014-15 to 2.80 in 2024-25, peaking at 2.96 in 2022-23. Similar numbers
and trends are prevalent when looking at established goalies only. This
makes sense given that approximately 85% and 84% of the shots against
and goals against happened on established goalies, respectively.</p>
<p>The overall trend of higher goals against and lower save percentages
indicates that goalies are getting scored on more in the last decade
than they were previously. It is unclear on why this is happening, but I
suspect that it is due to the increased skill level of modern day
forwards/defencemen. The NHL substantially restricted the size of goalie
equipment at the start of the 2005-06 season, which explains the large
dip in save percentage and large spike in goals against average during
that season.</p>
<pre class="r"><code># Explore correlation between performance stats and physical attributes
established_goalies |&gt;
  select(savePct, goalsAgainstAverage, wins, height, weight) |&gt;
  cor() |&gt;
  ggcorrplot(lab = T, title = &quot;Correlation Between Performance and Physical\nAttributes of Established NHL Goalies&quot;)</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
<pre class="r"><code># Calculate the average SV% and GAA across each season for established goalies
# grouped by undersized status
established_league_stats_by_season_undersized = established_goalies |&gt;
  group_by(seasonStartYear, seasonEndYear, undersized) |&gt;
  summarize(
    mean_savePct = sum(saves) / sum(shotsAgainst),
    mean_goalsAgainstAverage = (sum(goalsAgainst) * 60 * 60) / sum(timeOnIce),  # notice secs to mins conversion
    mean_win_percentage = sum(wins) / sum(gamesPlayed),
    .groups = &quot;drop&quot;
  ) |&gt;
  ungroup() |&gt;
  arrange(seasonStartYear, undersized)

established_league_stats_by_season_undersized</code></pre>
<pre><code>## # A tibble: 47 × 6
##    seasonStartYear seasonEndYear undersized mean_savePct mean_goalsAgainstAver…¹
##              &lt;int&gt;         &lt;int&gt; &lt;lgl&gt;             &lt;dbl&gt;                   &lt;dbl&gt;
##  1            2000          2001 FALSE             0.907                    2.53
##  2            2000          2001 TRUE              0.902                    2.69
##  3            2001          2002 FALSE             0.909                    2.45
##  4            2001          2002 TRUE              0.908                    2.50
##  5            2002          2003 FALSE             0.912                    2.44
##  6            2002          2003 TRUE              0.897                    2.83
##  7            2003          2004 FALSE             0.914                    2.38
##  8            2003          2004 TRUE              0.913                    2.27
##  9            2005          2006 FALSE             0.903                    2.89
## 10            2005          2006 TRUE              0.902                    2.71
## # ℹ 37 more rows
## # ℹ abbreviated name: ¹​mean_goalsAgainstAverage
## # ℹ 1 more variable: mean_win_percentage &lt;dbl&gt;</code></pre>
<pre class="r"><code># Plot the average league wide save percentage of each season for established goalies
# grouped by undersize status
established_league_stats_by_season_undersized |&gt;
  ggplot(aes(x = seasonStartYear, y = mean_savePct, color = undersized)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(
    title = &quot;Average League-Wide Save Percentage by Season\nBetween Short and Tall Established NHL Goalies&quot;,
    x = &quot;Season&quot;,
    y = &quot;Average Save %&quot;,
    color = &quot;Undersized?&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = &quot;0&quot;), str_pad(seq(1, 25, 2), 2, pad = &quot;0&quot;), sep = &quot;-&quot;)
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<pre class="r"><code># Plot the average league wide GAA of each season for established goalies
# grouped by undersize status
established_league_stats_by_season_undersized |&gt;
  ggplot(aes(x = seasonStartYear, y = mean_goalsAgainstAverage, color = undersized)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(
    title = &quot;Average League-Wide Goals Against Average by\nSeason Between Short and Tall Established NHL Goalies&quot;,
    x = &quot;Season&quot;,
    y = &quot;Average GAA&quot;,
    color = &quot;Undersized?&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = &quot;0&quot;), str_pad(seq(1, 25, 2), 2, pad = &quot;0&quot;), sep = &quot;-&quot;)
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<pre class="r"><code># Plot the average league wide win percentage of each season for established goalies
# grouped by undersize status
established_league_stats_by_season_undersized |&gt;
  ggplot(aes(x = seasonStartYear, y = mean_win_percentage, color = undersized)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(
    title = &quot;Average League-Wide Win Percentage by Season\nBetween Short and Tall Established NHL Goalies&quot;,
    x = &quot;Season&quot;,
    y = &quot;Average Win %&quot;,
    color = &quot;Undersized?&quot;
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2024, 2),
    labels = paste(str_pad(seq(0, 24, 2), 2, pad = &quot;0&quot;), str_pad(seq(1, 25, 2), 2, pad = &quot;0&quot;), sep = &quot;-&quot;)
  )</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-56-1.png" width="672" /></p>
<p>There does not appear to be any significant correlation or visual
trend between being an undersized (established) goalie and having good
performance statistics. The correlation coefficient between height and
save percentage is 0.08. Similarly, the correlation coefficient between
height and goals against average is 0.08.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
